name: cbsfmrilogging
version: 0.0.0
architectures:
  - x86_64
build:
  kind: neurodocker
  base-image: ubuntu:24.04
  pkg-manager: apt
  directives:
    - file:
        name: cbsfmrilogging.py
        contents: |-
          import ismrmrd
          import os
          import logging
          import traceback
          import mrdhelper
          import constants

          # ------------------------------------------------------------------------
          #   Purpose: This script just dumps all header data from
          #   images 
          #
          #   Script also logs to logging.info (.utr file) to analyse input order
          #   and directly compare with other logging processes.
          #
          #   TODO: Handle k-space/acquisition 
          #   TODO: Make YAML in neurocontainer builder
          #   
          # ------------------------------------------------------------------------


          def process(connection, config, mrdHeader):
              try:
                  logging.info("MANUAL_LOG: Incoming dataset contains %d encodings", len(mrdHeader.encoding))
                  logging.info("MANUAL_LOG: First encoding is the following:\n%s", mrdHeader.encoding[0])
                  try:
                      logging.info("MANUAL_LOG: First full mrdHeader is the following:\n%s",mrdHeader[0])
                      logging.info("MANUAL_LOG: First full Config:\n%s",config[0])
                  except:
                      logging.info("MANUAL_LOG: First full mrdHeader failed. logging mrdHeader:\n%s",mrdHeader)
                      logging.info("MANUAL_LOG_ERROR: First full config failed logging config:\n%s",config)
              except:
                  logging.info("MANUAL_LOG: Improperly formatted metadata: \n%s",mrdHeader)

              try:
                  for item in connection:
                      
                      # ----------------------------------------------------------
                      # Raw k-space data messages
                      # ----------------------------------------------------------
                      if isinstance(item, ismrmrd.Acquisition):
                          logging.info("MANUAL_LOG: Raw k-space data recieved, logging AcquisitionHeader:\n%s",item.AcquisitionHeader())
                          try:
                              logging.info("MANUAL_LOG_TESTING: Logging AcquisitionHeader via item.getHead():\n%s",item.getHead())
                          except:
                              logging.info("MANUAL_LOG_TESTING-FAILED: Could not log AcquisitionHeader:\n%s",item.AcquisitionHeader())
                          raise Exception("MANUAL_LOG: Raw k-space data is not supported by this module")
                      # ----------------------------------------------------------
                      # Image data messages
                      # ----------------------------------------------------------
                      elif isinstance(item, ismrmrd.Image):
                          logging.info("MANUAL_LOG: Image data recieved, logging ImageHeader:\n%s",item.ImageHeader())
                          logging.info("MANUAL_LOG: Processing a group of images because series index changed to %d", item.image_series_index)# If no **A then no this
                          try:
                              logging.info("MANUAL_LOG_TESTING: item.image_series_index:%s,item.imtype:%s,item.phase:%s,item.repetition:%s",item.image_series_index,item.image_type,item.phase,item.repetition)
                          except:
                              logging.info("MANUAL_LOG_TESTING: item.image_series_index, item.phase and item.repetition failed.")
                          tmpMeta = ismrmrd.Meta.deserialize(item.attribute_string)
                          tmpMeta['Keep_image_geometry']    = 1
                          item.attribute_string = tmpMeta.serialize()
                          connection.send_image(item)
                          continue

                      elif item is None:
                          break
                      else:
                          raise Exception("MANUAL_LOG: Unsupported data type %s", type(item).__name__)

              except Exception as e:
                  logging.error("MANUAL_ERROR: "+traceback.format_exc())
                  connection.send_logging(constants.MRD_LOGGING_ERROR, traceback.format_exc())

                  # Close connection without sending MRD_MESSAGE_CLOSE message to signal failure
                  connection.shutdown_close()
              finally:
                  try:
                      connection.send_close()
                  except:
                      logging.error("MANUAL_LOG: Failed to send close message!")
    - environment:
        DEBIAN_FRONTEND: noninteractive
    - install: bzip2 ca-certificates git wget build-essential python3-pip python-is-python3
    - include: macros/openrecon/neurodocker.yaml
    - install:
        - gcc-aarch64-linux-gnu cmake make build-essential
    - workdir: /opt/code
    - copy:
        - cbsfmrilogging.py
        - /opt/code/python-ismrmrd-server/cbsfmrilogging.py
readme: |-
  ----------------------------------
  ## cbsfmrilogging/{{ context.version }} ##
  container for logging all header data from acquisition and image data for OpenRecon via Neurocontainer

  you can build this recipe with:
  ```bash
  source .venv/bin/activate
  ./builder/build.py generate cbsfmrilogging --recreate --build --login --architecture x86_64
  ```

  ----------------------------------
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAADsUlEQVRIS7WVbUjTWxzHv2erucc2VwaVvfCSuOl6cDW7BVsQinjBAs0SSzMiwZDswWp3XXsA71WsXgWhpZCvBMkwiN5UEA1rg0atpVOiKGfTclulW2mudXfO2j/nJAj1wJ/B2f///fwevud3yOZzge/hBbro7/Rntvtk01k/U58L8R9CMVoMMF/iVJf8eWYsDvC7Gc0UOQs6LEQ2nh6NAUwV/zb5BcHPH0AEUvAFkhnL+Cvx8AcgWbWfOAAVD4VC8Lss8D5rh9z/ECqVCjabDcEV+ZD9kYPX13cxQ0xdiZkHIFqug3ilAWSBkEVOxVmJdP985FwUCn3DsOUSMsWP0dHRAbFYzOnY7XZs1m/F5zEfC4IQwv0XDAZhNpuxveI8lmz5F3xhIpct2XDqA+eiMZcVsFajr68PPT09yMvLg8fjQVlZGZqamtDd3Q29Xs8Azc3NqK+vh1QqRW1tLYqLi1FZWYkbL1ZBllYQC4i66NWNcnRePgyDwQC5XA4kasJlycY783+oq6uDTqdDbm4uAzQ0NMBkMrEsNBoNHA4HjEYjmu+MQrmx5idgvcnHSkQbar+QjIGBAUxMTCA1NRXqgz3gi5Tw2K5i+P5priQU4HQ6YbFYIJPJkJ2dDYlEgqSkJAi0JshUOyIA6iLt314GmAyM4PklNbxeL1wuF3T6v5BWYWMvjr68A9fNvTEAGoTf7wePx4NCoWBZ5efn4/EXA6SqIq7RJNPoiWQQnIDjYjJ6e3uRkpICkUiE9Oo3AG8BvE+vYYP4IUpLS1mtp5dIKBSyoOij1Wqxcr8DPH5CxEXrTo5wLnpz6yCunN2JoqIiZGRkwLesFMIkDQZvVcD55AGoW9RqdRyApma1WllZlUolVuw2gy9eGgGsPfGec9Hoq3sIPKiG2+2Gz+dDYWEh+vv70djYiPLycpSUlKC9vZ0BOjs70dLSAoFAgKqqKuTk5KCrqwsFBQVI3mcHiWZAAVEXhYJf4bpdhW1Zi9Da2so+jq62tjYGiR7G6eeAHkbabEGmEZK0H02mGaw5/i5mVIz7XmLo7kmMuy2snrSB9BDRpio3nYDvUWPcSY5uKLJqIEnfw0XPXLS6Zjh22NFx8TWAwKAFk/4hhMLN54sWQ7BYBX6CHOMjzrBDwp9G747w+7yFEpAEBfjSZMaKWpTNIs2xoZ+AKTMkZoTPYp9kHHVHALMQ+VUwJP3I28iFOcN1ORf7EcA8ibNzoD48GA+Yw4yIqtoV56K5LBdJOzQwry76H0tMj7XJU3hkAAAAAElFTkSuQmCC
categories:
  - functional imaging
